home_ip_address = "YOUR_HOME_IP_HERE/32"
ssh_public_key_path = "/path/to/your/.ssh/id_rsa.pub"
admin_username = "your_desired_username"
minecraft_memory = "3G"
contact_email = "example@example.com"
cloudflare_api_token = "your_cloudflare_api_token_here"
cloudflare_zone_id = "your_cloudflare_zone_id_here"