name: 'Terraform Workload'

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Type "apply" to build/update, or "destroy" to tear down the infrastructure'
        required: true
        default: 'apply'
  
permissions:
  id-token: write
  contents: read

jobs: 
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_OIDC: true
      TF_VAR_remote_state_resource_group_name: ${{ secrets.REMOTE_STATE_RESOURCE_GROUP_NAME }}
      TF_VAR_remote_state_storage_account_name: ${{ secrets.REMOTE_STATE_STORAGE_ACCOUNT_NAME }}
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      TF_VAR_home_ip_address: ${{ secrets.HOME_IP_ADDRESS }}
      TF_VAR_admin_username: ${{ vars.ADMIN_USERNAME }}
      TF_VAR_contact_email: ${{ vars.CONTACT_EMAIL }}
      TF_VAR_minecraft_memory: ${{ vars.MINECRAFT_MEMORY }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="resource_group_name=${{ secrets.REMOTE_STATE_RESOURCE_GROUP_NAME }}" \
          -backend-config="storage_account_name=${{ secrets.REMOTE_STATE_STORAGE_ACCOUNT_NAME }}" \
          -backend-config="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
      working-directory: ./workloads/minecraft

    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: ./workloads/minecraft

    - name: Terraform Action
      run: |
        # Set a local variable: Use the input if it exists, otherwise default to 'apply'
        ACTION=${{ github.event.inputs.action || 'apply' }}
        
        echo "Executing action: $ACTION"

        if [ "$ACTION" == "apply" ]; then
          terraform apply -auto-approve -input=false
        elif [ "$ACTION" == "destroy" ]; then
          terraform destroy -auto-approve -input=false
        else
          echo "Invalid action. Please enter 'apply' or 'destroy'."
          exit 1
        fi
      working-directory: ./workloads/minecraft
